FROM evarga/jenkins-slave

COPY conf/sources.list.trusty /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y wget curl

# Standard SSH port
EXPOSE 22

# Default command
CMD ["/usr/sbin/sshd", "-D"]
